services:
  - type: web
    name: smart-reminder
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: TZ
        value: Asia/Kolkata
